CREATE TABLE Review 
(
	ID		INT		IDENTITY(1,1)	PRIMARY KEY,
	NAME	VARCHAR(50)		NOT NULL,
	TITLE	VARCHAR(100)	NOT NULL,
	POSTDATE	DATETIME	DEFAULT(GetDate()),
	POSTIP		VARCHAR(15) NULL
)
GO

INSERT INTO dbo.Review 
(NAME, TITLE, POSTIP)
VALUES
('test', 'title test', '127.0.0.1');
GO