CREATE PROCEDURE dbo.SearchMemo
(
	@SEARCHFIELD NVARCHAR(10),
	@SEARCHQUERY NVARCHAR(50)
)

AS

DECLARE @STRSQL NVARCHAR(250)

SET @STRSQL = '
	SELECT NUM, NAME, EMAIL, TITLE, POSTDATE, POSTIP 
	FROM dbo.Memos 
	WHERE ' + @SEARCHFIELD + 'LIKE %' + @SEARCHQUERY + '% ORDER BY NUM DESC';

EXEC @STRSQL;
GO