CREATE TABLE dbo.Memos
(
	NUM		Int Identity(1, 1) Primary key,
	NAME	NVARCHAR(25) NOT NULL,
	EMAIL	NVARCHAR(100) NULL,
	TITLE	NVARCHAR(150) NOT NULL,
	POSTDATE	DATETIME DEFAULT(GETDATE()),
	POSTIP	NVARCHAR(15) NULL
)

GO
-- #1 입력문 INSERT INTO
INSERT INTO Memos
VALUES (
	N'이안', N'ian@urock.kr', N'데이터베이스 테스트', GETDATE(), '127.0.0.1'
);

GO

-- #2 출력문 SELECT * FROM [DB]
SELECT NUM, NAME, EMAIL, TITLE, POSTDATE, POSTIP FROM dbo.Memos ORDER BY NUM DESC;
GO

-- #3 상세 출력 SELECT * FROM [DB] WEHRE ID = ##
SELECT NUM, NAME, EMAIL, TITLE, POSTDATE, POSTIP FROM dbo.Memos WHERE NUM = 1;
GO

-- #4 수정 UPDATE [DB] SET 
UPDATE dbo.Memos SET NAME= N'성우', EMAIL= N'SRANG03@NAVER.COM', POSTIP='127.0.1.2' WHERE NUM = 1;
-- ROLLBACK TRAN
COMMIT TRAN
GO

-- #5 삭제 DELETE FROM [DB] WHERE ID = ##
BEGIN TRAN
	DELETE FROM dbo.Memos 
	WHERE NUM = 1
-- ROLLBACK TRAN
COMMIT TRAN
GO

-- #6 검색 SELECT
SELECT * FROM dbo.Memos WHERE NAME LIKE '%안%'
GO



