CREATE PROCEDURE [dbo].[ModifyMemo]
(
	@ID			INT,
	@NAME		NVARCHAR(25),
	@EMAIL		NVARCHAR(100),
	@TITLE		NVARCHAR(150),
	@POSTIP		NVARCHAR(15)
)
AS
	BEGIN TRANSACTION 
		UPDATE dbo.Memos SET
			NAME = @NAME, 
			EMAIL = @EMAIL,
			TITLE = @TITLE,
			POSTIP = @POSTIP

		WHERE ID = @ID
	COMMIT TRANSACTION
GO
